services:
  skylink-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: skylink_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=amineSERRAR52479.
      - MSSQL_PID=Developer
    volumes:
      - skylink_data:/var/opt/mssql

volumes:
  skylink_data:
